(()=>{
  const ide=window.MatrixIDE,actions=['send','explain','debug','refactor','optimize','tests','selectionOnly'];
  const findFile=path=>{const normalized=ide.normalize(path);if(ide.activeFile&&ide.normalize(ide.activeFile.path)===normalized)return ide.activeFile;for(const project of ide.projects.values())for(const root of project.rootPaths){const base=ide.normalize(root);if(normalized.toLowerCase().startsWith(base.toLowerCase()+'/'))return {project,root,path,relative:normalized.slice(base.length+1)};}return null;};
  ide.modules.editor={
    async open(file,preview){const scope=ide.findScope();const meta=await ide.request('read-file-metadata',{hostId:'local',path:file.path,contentSampleByteLimit:1024,contentSampleMaxFileBytes:20971520});if(meta.sizeBytes>20971520){ide.noticeKey('error.fileTooLarge');return null;}const result=ide.api.openFile(scope,file.path,{hostId:'local',cwd:file.root,workspaceRoot:file.root,workspaceRoots:file.project.rootPaths,target:'right',fileOpenOrigin:'app',isPreview:preview});if(!result)throw Error(ide.t('error.openFile'));const model=ide.api.panel('right'),tab=scope.get(model.activeTab$);if(result.status==='opened'&&tab?.props?.editor?.kind==='markdown'&&typeof model.updateTabState==='function')model.updateTabState(scope,tab.tabId,s=>({...s,markdownMode:'source'}));if(!preview&&tab?.tabId&&typeof model.pinTab==='function')model.pinTab(scope,tab.tabId);ide.activeFile=file;document.querySelectorAll('.mx-ide-tree-row[aria-selected]').forEach(e=>e.setAttribute('aria-selected',String(ide.normalize(e.title)===ide.normalize(file.path))));ide.editorController?.update();return result;},
    install(){let pending=0,menu=null;const mounted=new Map(),rootListeners=new Map(),shadowObservers=new Map();
      function nativeActiveFile(){try{const scope=ide.findScope(),model=ide.api.panel('right'),tab=scope.get(model.activeTab$);return tab?.props?.path?findFile(tab.props.path):null;}catch{return null;}}
      function selection(root){const sel=root.getSelection?.()||document.getSelection();if(!sel||sel.isCollapsed||!sel.rangeCount)return null;const range=sel.getRangeAt(0),startEl=range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement,endEl=range.endContainer.nodeType===1?range.endContainer:range.endContainer.parentElement;const a=startEl?.closest('[data-line]'),b=endEl?.closest('[data-line]');if(!a||!b||a.getRootNode()!==root||b.getRootNode()!==root)return null;const code=sel.toString();if(!code.trim())return null;let end=+b.dataset.line;const prefix=range.cloneRange();prefix.selectNodeContents(b);prefix.setEnd(range.endContainer,range.endOffset);if(end>+a.dataset.line&&!prefix.toString().length)end--;return{code,start:+a.dataset.line,end};}
      function closeMenu(){menu?.remove();menu=null;}
      function showMenu(anchor,record){closeMenu();if(!record.selection)return;menu=ide.element('div','mx-ide-menu');menu.dataset.matrixIdeOwned='';menu.setAttribute('role','menu');for(const task of actions){const b=ide.localElement('button',null,'task.'+task);b.setAttribute('role','menuitem');b.onpointerdown=e=>e.preventDefault();b.onclick=ide.safe(()=>{ide.modules.context.selection(record.file,task,record.selection);closeMenu();});menu.appendChild(b);}const r=anchor.getBoundingClientRect();menu.style.top=Math.min(r.bottom+5,innerHeight-280)+'px';menu.style.left=Math.max(8,Math.min(r.left,innerWidth-225))+'px';document.body.appendChild(menu);}
      function capture(record,root){const current=selection(root);record.selection=current;record.selectButton.disabled=!current;ide.label(record.selectButton,current?'editor.selection':'editor.selectCode',current?{start:current.start,end:current.end}:{});if(current)record.file=nativeActiveFile()||record.file;}
      function update(){pending=0;if(ide.disposed)return;const active=nativeActiveFile();if(active){ide.activeFile=active;document.querySelectorAll('.mx-ide-tree-row[aria-selected]').forEach(e=>e.setAttribute('aria-selected',String(ide.normalize(e.title)===ide.normalize(active.path))));}
        for(const host of document.querySelectorAll('diffs-container')){const root=host.shadowRoot;if(root&&!shadowObservers.has(host)){const observer=new MutationObserver(()=>{const content=root.querySelector('[data-content][contenteditable="true"]'),record=mounted.get(host);if(content&&(!record||content.getAttribute('aria-label')!==record.file.path))queue();});observer.observe(root,{subtree:true,childList:true,attributes:true,attributeFilter:['aria-label']});shadowObservers.set(host,observer);}const content=root?.querySelector('[data-content][contenteditable="true"]');if(!content)continue;const path=content.getAttribute('aria-label'),file=findFile(path||'');if(!file)continue;let record=mounted.get(host);if(!record){const toolbar=ide.element('div','mx-ide-toolbar');toolbar.dataset.matrixIdeOwned='';ide.label(toolbar,'editor.tools',{},'aria-label');const add=ide.localElement('button',null,'editor.addFile'),work=ide.localElement('button',null,'editor.workFile'),selectButton=ide.localElement('button','mx-ide-selection','editor.selectCode');selectButton.disabled=true;const status=ide.element('span','mx-ide-save-status');status.setAttribute('role','status');toolbar.append(add,work,status,selectButton);record={file,toolbar,selectButton,status,selection:null};add.onclick=ide.safe(()=>ide.modules.context.whole(record.file,false));work.onclick=ide.safe(()=>ide.modules.context.whole(record.file,true));selectButton.onpointerdown=e=>e.preventDefault();selectButton.onclick=()=>showMenu(selectButton,record);host.parentElement.insertBefore(toolbar,host);mounted.set(host,record);
          const onSelection=()=>setTimeout(()=>capture(record,root),0);root.addEventListener('mouseup',onSelection);root.addEventListener('keyup',onSelection);root.addEventListener('selectionchange',onSelection);rootListeners.set(root,onSelection);const theme=document.createElement('style');theme.dataset.matrixIdeOwned='';theme.textContent=':host{--diffs-bg:#070d09;--diffs-bg-gutter:#0b160f;--diffs-fg:#c2ebcc;--diffs-selection:#245e36;}[data-gutter]{color:#668e73;}';root.appendChild(theme);record.theme=theme;
        }record.file=file;try{const tab=ide.findScope().get(ide.api.panel('right').activeTab$);if(ide.normalize(tab?.props?.path||'')===ide.normalize(file.path)){ide.label(record.status,tab.hasUnsavedChanges?'editor.unsaved':'editor.saved');record.status.style.color=tab.hasUnsavedChanges?'#eed389':'#71967c';}}catch{}}
        for(const[host,record]of mounted)if(!host.isConnected){record.toolbar.remove();record.theme.remove();const root=host.shadowRoot,listener=rootListeners.get(root);if(listener){root.removeEventListener('mouseup',listener);root.removeEventListener('keyup',listener);root.removeEventListener('selectionchange',listener);rootListeners.delete(root);}mounted.delete(host);}for(const[host,observer]of shadowObservers)if(!host.isConnected){observer.disconnect();shadowObservers.delete(host);}
      }
      const queue=records=>{if(pending||ide.disposed)return;if(records&&records.every(r=>r.target.closest?.('.mx-ide-toolbar,.mx-ide-menu,.mx-ide-tree,.mx-ide-tabs')))return;pending=setTimeout(update,120);};const observer=new MutationObserver(queue);observer.observe(document.body,{subtree:true,childList:true});
      const outside=e=>{if(menu&&!menu.contains(e.target)&&!e.target.closest('.mx-ide-selection'))closeMenu();};const escape=e=>{if(e.key==='Escape')closeMenu();};const changed=()=>requestAnimationFrame(()=>{for(const[host,record]of mounted)if(host.isConnected)capture(record,host.shadowRoot);});document.addEventListener('selectionchange',changed);document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);update();
      ide.cleanups.push(()=>{observer.disconnect();for(const observer of shadowObservers.values())observer.disconnect();shadowObservers.clear();clearTimeout(pending);closeMenu();document.removeEventListener('selectionchange',changed);document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);for(const[root,listener]of rootListeners){root.removeEventListener('mouseup',listener);root.removeEventListener('keyup',listener);root.removeEventListener('selectionchange',listener);}for(const record of mounted.values()){record.toolbar.remove();record.theme.remove();}});
      return {update,selection,mounted};
    }
  };
})();
