(()=>{
  const ide=window.MatrixIDE,heavy=new Set(['.git','node_modules','vendor','build','dist','cache','.cache','__pycache__','.next','.nuxt','target','venv','.venv']);
  const icon=(entry)=>entry.type==='directory'?'▸':({js:'JS',mjs:'JS',cjs:'JS',ts:'TS',tsx:'TS',jsx:'JS',json:'{}',css:'#',scss:'#',html:'<>',php:'PHP',py:'PY',md:'MD',png:'▧',jpg:'▧',svg:'▧',zip:'ZIP'})[entry.name.split('.').pop().toLowerCase()]||'·';
  ide.modules.tree={create(project){
    const tree=ide.element('div','mx-ide-tree');tree.setAttribute('role','tree');ide.label(tree,'tree.aria',{project:project.name},'aria-label');const tools=ide.element('div','mx-ide-tree-tools'),name=ide.localElement('span',null,'tabs.files'),refresh=ide.element('button',null,'↻');ide.label(refresh,'tree.refresh',{},'title');ide.label(refresh,'tree.refresh',{},'aria-label');tools.append(name,refresh);tree.appendChild(tools);const body=ide.element('div');tree.appendChild(body);const cache=new Map(),expanded=new Set(ide.initialProjectState.get(project.id)?.expanded||[]);let disposed=false,started=false;const abort=new AbortController();
    const directory=async(root,rel,parent,depth)=>{parent.replaceChildren(ide.localElement('div','mx-ide-tree-message','tree.loading'));try{let entries=cache.get(root+'\0'+rel);if(!entries){const result=await ide.request('workspace-directory-entries',{hostId:'local',workspaceRoot:root,directoryPath:rel,includeHidden:false},abort.signal);entries=result.entries.filter(e=>!heavy.has(e.name.toLowerCase())).sort((a,b)=>(a.type===b.type?0:a.type==='directory'?-1:1)||a.name.localeCompare(b.name,ide.i18n.locale,{numeric:true}));cache.set(root+'\0'+rel,entries);}if(disposed)return;parent.replaceChildren();if(!entries.length){parent.appendChild(ide.localElement('div','mx-ide-tree-message','tree.empty'));return;}let shown=0;const more=()=>{parent.querySelector(':scope > .mx-ide-more')?.remove();for(const entry of entries.slice(shown,shown+100)){const node=ide.element('div'),button=ide.element('button','mx-ide-tree-row'),glyph=ide.element('span','mx-ide-tree-icon',icon(entry)),label=ide.element('span','mx-ide-tree-label',entry.name);button.style.paddingLeft=(depth*10+3)+'px';button.setAttribute('role','treeitem');button.title=ide.join(root,entry.path);button.dataset.path=entry.path;button.append(glyph,label);node.appendChild(button);parent.appendChild(node);
      glyph.setAttribute('aria-hidden','true');button.dataset.kind=entry.type;
      if(entry.type==='directory'){glyph.classList.add('mx-ide-tree-chevron');glyph.textContent='';button.setAttribute('aria-expanded','false');const children=ide.element('div');children.setAttribute('role','group');children.hidden=true;node.appendChild(children);button.onclick=ide.safe(async()=>{const open=children.hidden;children.hidden=!open;button.setAttribute('aria-expanded',String(open));if(open){expanded.add(entry.path);if(!children.childNodes.length)await directory(root,entry.path,children,depth+1);}else expanded.delete(entry.path);});if(expanded.has(entry.path)){children.hidden=false;button.setAttribute('aria-expanded','true');directory(root,entry.path,children,depth+1);}}
      else{button.setAttribute('aria-selected',String(ide.activeFile?.path===button.title));button.onclick=ide.safe(()=>ide.modules.editor.open({project,root,path:ide.join(root,entry.path),relative:entry.path},true));button.ondblclick=ide.safe(()=>ide.modules.editor.open({project,root,path:ide.join(root,entry.path),relative:entry.path},false));}}
      shown+=100;if(shown<entries.length){const load=ide.localElement('button','mx-ide-more','tree.more',{count:entries.length-shown});load.onclick=more;parent.appendChild(load);}};more();}catch(e){if(!disposed&&e.name!=='AbortError')parent.replaceChildren(ide.localElement('div','mx-ide-tree-message','tree.error',{message:e.message}));}};
    const start=()=>{if(started||disposed)return;started=true;if(project.rootPaths.length===1)directory(project.rootPaths[0],'',body,0);else for(const root of project.rootPaths){const title=ide.element('div','mx-ide-tree-message',ide.normalize(root).split('/').pop()),container=ide.element('div');body.append(title,container);directory(root,'',container,0);}};
    refresh.onclick=()=>{cache.clear();expanded.clear();body.replaceChildren();started=false;start();};return {element:tree,start,dispose(){disposed=true;abort.abort();tree.remove();}};
  }};
})();
