(()=>{
  const ide=window.MatrixIDE;
  ide.modules.projects={install(){const states=new Map();let timer=0;
    const update=()=>{timer=0;if(ide.disposed)return;for(const row of document.querySelectorAll('[data-app-action-sidebar-project-row]')){const id=row.dataset.appActionSidebarProjectId,project=ide.projects.get(id),group=row.closest('[data-sidebar-project-container-id][role="listitem"]');if(!project||!group)continue;const chat=Array.from(group.children).find(e=>e.hasAttribute('aria-hidden'));if(!chat)continue;let s=states.get(id);if(!s){s={mode:ide.initialProjectState.get(id)?.mode||'chats',tree:ide.modules.tree.create(project),tabs:ide.element('div','mx-ide-tabs')};s.tabs.dataset.matrixIdeOwned='';s.tree.element.dataset.matrixIdeOwned='';s.tabs.setAttribute('role','tablist');ide.label(s.tabs,'project.view',{project:project.name},'aria-label');for(const[mode,label]of [['chats','tabs.chats'],['files','tabs.files']]){const b=ide.localElement('button',null,label);b.setAttribute('role','tab');b.dataset.mode=mode;b.onclick=e=>{e.stopPropagation();s.mode=mode;apply(s,row,chat);};s.tabs.appendChild(b);}states.set(id,s);}s.row=row;s.chat=chat;if(s.tabs.parentElement!==group){group.insertBefore(s.tabs,chat);group.insertBefore(s.tree.element,chat);}apply(s,row,chat);}}
    function apply(s,row,chat){row=s.row||row;chat=s.chat||chat;const open=row.getAttribute('aria-expanded')==='true';s.tabs.hidden=!open;s.tabs.style.display=open?'flex':'none';s.tree.element.hidden=!open||s.mode!=='files';chat.classList.toggle('mx-ide-chat-hidden',open&&s.mode==='files');for(const b of s.tabs.children)b.setAttribute('aria-selected',String(b.dataset.mode===s.mode));if(open&&s.mode==='files')s.tree.start();}
    const queue=records=>{if(timer||ide.disposed)return;if(records&&records.every(r=>r.target.closest?.('.mx-ide-tree,.mx-ide-tabs')))return;timer=setTimeout(update,80);};const observer=new MutationObserver(queue);observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-expanded']});update();
    const api={states,update,async refresh(){await ide.refreshProjects();update();}};const refreshTimer=setInterval(()=>api.refresh().catch(e=>console.warn('[Matrix IDE projects]',e)),30000);ide.cleanups.push(()=>{observer.disconnect();clearTimeout(timer);clearInterval(refreshTimer);for(const s of states.values()){s.chat?.classList.remove('mx-ide-chat-hidden');s.tabs.remove();s.tree.dispose();}});return api;
  }};
})();
